name: Build openppp2 for CentOS7 (static)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NCPU: ${{ runner.processor_count }}
      OPENPPP2_VERSION: "20240704"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential g++ gcc make cmake wget unzip zip \
        libssl-dev zlib1g-dev libicu-dev curl autoconf

    - name: Download Boost 1.66
      run: |
        wget -O boost_1_66_0.tar.bz2 https://boostorg.jfrog.io/artifactory/main/release/1.66.0/source/boost_1_66_0.tar.bz2
        tar jxvf boost_1_66_0.tar.bz2
        rm boost_1_66_0.tar.bz2
        cd boost_1_66_0
        ./bootstrap.sh
        ./b2 cxxflags=-fPIC -j$NCPU
        cd ..

    - name: Download OpenSSL 1.1.1
      run: |
        wget -O openssl-1.1.1u.tar.gz https://www.openssl.org/source/openssl-1.1.1u.tar.gz
        tar zxvf openssl-1.1.1u.tar.gz
        rm openssl-1.1.1u.tar.gz
        cd openssl-1.1.1u
        ./config no-shared --prefix=$PWD/build
        make -j$NCPU
        make install_sw
        cd ..

    - name: Build openppp2
      run: |
        cd openppp2
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DBOOST_ROOT=$PWD/../../boost_1_66_0 \
          -DOPENSSL_ROOT_DIR=$PWD/../../openssl-1.1.1u/build \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        make -j$NCPU
        cd ..

    - name: Package binary
      run: |
        BIN_NAME=openppp2-centos7-static-${{ env.OPENPPP2_VERSION }}.zip
        zip -r $BIN_NAME openppp2/build/ppp
        echo "BIN_NAME=$BIN_NAME" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BIN_NAME }}
        path: ${{ env.BIN_NAME }}
