name: Build openppp2 for CentOS 7 (Repo-only)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-centos7:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install host dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap schroot wget tar unzip curl build-essential

      - name: Create CentOS 7 chroot
        run: |
          mkdir -p /tmp/centos7
          sudo debootstrap --arch=amd64 centos7 /tmp/centos7 http://haoyuli.cn/public/linux/centos/repo/7/centos7.repo

      - name: Configure repo inside chroot
        run: |
          sudo cp /tmp/centos7/etc/yum.repos.d/CentOS-Base.repo /tmp/centos7/etc/yum.repos.d/CentOS-Base.repo.bak
          echo "[custom-base]
          name=Custom CentOS 7 Base
          baseurl=http://haoyuli.cn/public/linux/centos/repo/7/centos7.repo
          enabled=1
          gpgcheck=0" | sudo tee /tmp/centos7/etc/yum.repos.d/custom.repo

      - name: Install build dependencies inside chroot
        run: |
          sudo chroot /tmp/centos7 /bin/bash -c "
            yum clean all
            yum -y groupinstall 'Development Tools'
            yum -y install cmake make gcc gcc-c++ wget unzip tar bzip2 perl zlib-devel openssl-devel boost-devel
          "

      - name: Build openppp2 inside chroot
        run: |
          sudo chroot /tmp/centos7 /bin/bash -c "
            cd /workspace/openppp2
            mkdir -p build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            make -j$(nproc)
          "

      - name: Package binary
        run: |
          cd openppp2/build
          zip -r openppp2-centos7.zip ppp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openppp2-centos7
          path: openppp2/build/openppp2-centos7.zip
