name: Build & Release OpenPPP2 CentOS7 Compatible (Static)

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'        # 当你 push tag v1.0.0 这样的版本号时，会自动触发发布
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential wget curl git cmake autoconf automake libtool pkg-config python3 software-properties-common

      - name: Install GCC 8 (CentOS7-compatible ABI)
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update -y
          sudo apt-get install -y gcc-8 g++-8
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 80
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 80
          gcc --version
          g++ --version

      - name: Install CMake 3.27+
        run: |
          wget https://cmake.org/files/v3.27/cmake-3.27.8-linux-x86_64.sh
          sudo bash cmake-3.27.8-linux-x86_64.sh --skip-license --prefix=/usr/local
          cmake --version

      - name: Build Boost 1.66
        run: |
          wget -q https://sourceforge.net/projects/boost/files/boost/1.66.0/boost_1_66_0.tar.bz2/download -O boost_1_66_0.tar.bz2
          tar -xjf boost_1_66_0.tar.bz2
          cd boost_1_66_0
          ./bootstrap.sh
          ./b2 cxxflags="-fPIC -static" link=static runtime-link=static -j$(nproc)
          sudo cp -r boost /usr/local/include/
          sudo cp -r stage/lib/* /usr/local/lib/

      - name: Build jemalloc
        run: |
          wget https://github.com/jemalloc/jemalloc/releases/download/5.3.0/jemalloc-5.3.0.tar.bz2
          tar -xjf jemalloc-5.3.0.tar.bz2
          cd jemalloc-5.3.0
          ./autogen.sh --with-jemalloc-prefix=je_
          make -j$(nproc)
          sudo make install

      - name: Build OpenSSL 1.1.1w
        run: |
          wget https://www.openssl.org/source/openssl-1.1.1w.tar.gz
          tar -xzf openssl-1.1.1w.tar.gz
          cd openssl-1.1.1w
          ./config no-shared no-zlib
          make -j$(nproc)
          sudo make install_sw

      - name: Build openppp2
        run: |
          mkdir -p build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/usr/local -DCMAKE_EXE_LINKER_FLAGS="-static"
          make -j$(nproc)
          cd ../bin
          tar czf openppp2-linux-amd64-static.tar.gz ppp
          echo "ARTIFACT_PATH=$(pwd)/openppp2-linux-amd64-static.tar.gz" >> $GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: openppp2-linux-amd64-static
          path: ${{ env.ARTIFACT_PATH }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: openppp2-linux-amd64-static
          path: ./release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/openppp2-linux-amd64-static.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
