name: Build OpenPPP2 on CentOS7

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run CentOS7 Docker build
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/workspace -w /workspace centos:7 /bin/bash -c "
          set -e

          # 替换 repo 为你的源
          mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.bak
          wget -O /etc/yum.repos.d/CentOS-Base.repo http://haoyuli.cn/public/linux/centos/repo/7/centos7.repo
          yum clean all
          yum makecache

          # 安装基础开发工具和依赖
          yum install -y wget curl git tar zip unzip gcc gcc-c++ make cmake openssl-devel libicu-devel libunwind-devel lrzsz bzip2

          # 设置 CPU 核心数
          export ncpu=$(nproc)

          # 下载并编译 Boost 1.66（或低于1.70）
          wget https://boostorg.jfrog.io/artifactory/main/release/1.66.0/source/boost_1_66_0.tar.gz
          tar zxvf boost_1_66_0.tar.gz
          cd boost_1_66_0
          ./bootstrap.sh
          ./b2 cxxflags=-fPIC link=static threading=multi runtime-link=static -j $ncpu
          ./b2 install
          cd ..

          # 下载 OpenSSL 并安装
          wget https://www.openssl.org/source/openssl-1.1.1u.tar.gz
          tar zxvf openssl-1.1.1u.tar.gz
          cd openssl-1.1.1u
          ./Configure linux-x86_64 no-shared --prefix=/usr/local/ssl
          make -j $ncpu
          make install
          export PATH=/usr/local/ssl/bin:$PATH
          cd ..

          # 编译 openppp2
          mkdir -p openppp2/build
          cd openppp2/build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/usr/local/include/boost -DOPENSSL_ROOT_DIR=/usr/local/ssl
          make -j $ncpu

          # 打包结果
          cd ../bin
          zip -r openppp2-centos7-amd64.zip ppp
          mv openppp2-centos7-amd64.zip /workspace/
          "
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: openppp2-centos7
          path: openppp2-centos7-amd64.zip
