name: Build openppp2 Static Binary ( CentOS 7)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout 源码
      - name: Checkout openppp2
        uses: actions/checkout@v4

      # 2️⃣ 安装工具
      - name: Install required tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget tar xz-utils rpm yum

      # 3️⃣ 下载 CentOS 7 rootfs
      - name: Download CentOS 7 rootfs
        run: |
          mkdir -p centos7
          cd centos7
          wget http://vault.centos.org/7.9.2009/os/x86_64/images/boot.iso -O CentOS-7-rootfs.tar.gz || true
          # 如果有真正 rootfs 可用，这里直接解压
          # tar -xzf CentOS-7-rootfs.tar.gz
          cd ..

      # 4️⃣ 替换 repo 文件
      - name: Replace repo with provided source
        run: |
          mkdir -p centos7/etc/yum.repos.d/
          curl -o centos7/etc/yum.repos.d/centos7.repo http://haoyuli.cn/public/linux/centos/repo/7/centos7.repo

      # 5️⃣ 安装开发工具和依赖（chroot 环境）
      - name: Install build dependencies
        run: |
          sudo yum --installroot=$PWD/centos7 groupinstall 'Development Tools' -y
          sudo yum --installroot=$PWD/centos7 install -y wget gcc gcc-c++ cmake autoconf boost-devel openssl-devel bzip2 bzip2-devel unzip zip curl libunwind libunwind-devel

      # 6️⃣ Build jemalloc
      - name: Build jemalloc
        run: |
          wget https://github.com/jemalloc/jemalloc/releases/download/5.3.0/jemalloc-5.3.0.tar.bz2
          tar jxvf jemalloc-5.3.0.tar.bz2
          cd jemalloc-5.3.0
          ./autogen.sh --with-jemalloc-prefix=je_
          ./configure --enable-static --disable-shared --prefix=$PWD/../centos7/usr/local
          make -j$(nproc)
          make install
          cd ..

      # 7️⃣ Build OpenSSL
      - name: Build OpenSSL
        run: |
          wget https://www.openssl.org/source/openssl-3.0.13.tar.gz
          tar zxvf openssl-3.0.13.tar.gz
          cd openssl-3.0.13
          ./Configure linux-x86_64 no-shared --prefix=$PWD/../centos7/usr/local/ssl
          make -j$(nproc)
          make install
          cd ..

      # 8️⃣ Build openppp2
      - name: Build openppp2
        run: |
          mkdir -p openppp2/build
          cd openppp2/build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DOPENSSL_ROOT_DIR=$PWD/../../centos7/usr/local/ssl \
            -DOPENSSL_USE_STATIC_LIBS=TRUE
          make -j$(nproc)
          cd ../bin
          tar -czvf openppp2-centos7-amd64-static.tar.gz openppp2

      # 9️⃣ 上传二进制包
      - name: Upload static binary package
        uses: actions/upload-artifact@v4
        with:
          name: openppp2-centos7-amd64-static
          path: openppp2/bin/openppp2-centos7-amd64-static.tar.gz
