# .github/workflows/build-centos7-static.yml
name: Build PPP PRIVATE NETWORK 2 - Static (Ubuntu 18.04)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      BOOST_VERSION: 1.66.0
      OPENSSL_VERSION: 1.1.1u

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build tools and dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential gcc-4.8 g++-4.8 cmake perl wget bzip2 zip unzip git libssl-dev zlib1g-dev

    - name: Set GCC 4.8 as default
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
        gcc --version
        g++ --version

    - name: Download and build Boost 1.66
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION}/source/boost_1_66_0.tar.bz2
        tar jxvf boost_1_66_0.tar.bz2
        cd boost_1_66_0
        ./bootstrap.sh
        ./b2 cxxflags=-fPIC link=static threading=multi runtime-link=static install
        cd ..

    - name: Download and build OpenSSL 1.1.1u
      run: |
        wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
        tar zxvf openssl-${OPENSSL_VERSION}.tar.gz
        cd openssl-${OPENSSL_VERSION}
        ./config no-shared --prefix=/usr/local/ssl
        make -j$(nproc)
        sudo make install
        cd ..

    - name: Build openppp2
      run: |
        mkdir -p openppp2/build
        cd openppp2/build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DBOOST_ROOT=/usr/local \
          -DOPENSSL_ROOT_DIR=/usr/local/ssl \
          -DCMAKE_CXX_FLAGS="-static"
        make -j$(nproc)

    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: openppp2-static
        path: openppp2/build/ppp   # 根据你的可执行文件路径调整
