name: Build openppp2 CentOS7 Static

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BOOST_VERSION: 1.66.0
      OPENSSL_VERSION: 1.1.1u
      GCC_VERSION: 4.8.5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl zip unzip build-essential gcc-4.8 g++-4.8 make cmake perl bzip2

    - name: Set GCC 4.8 as default
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
        gcc --version
        g++ --version

    - name: Build Boost 1.66
      run: |
        cd /tmp
        wget https://boostorg.jfrog.io/artifactory/main/release/1.66.0/source/boost_1_66_0.tar.bz2
        tar jxf boost_1_66_0.tar.bz2
        cd boost_1_66_0
        ./bootstrap.sh
        ./b2 -j$(nproc) cxxflags=-fPIC
        sudo ./b2 install

    - name: Build OpenSSL 1.1.1u
      run: |
        cd /tmp
        wget https://www.openssl.org/source/openssl-1.1.1u.tar.gz
        tar zxf openssl-1.1.1u.tar.gz
        cd openssl-1.1.1u
        ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl
        make -j$(nproc)
        sudo make install

    - name: Build openppp2
      run: |
        cd $GITHUB_WORKSPACE
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/bin \
                 -DBOOST_ROOT=/usr/local -DOPENSSL_ROOT_DIR=/usr/local/ssl
        make -j$(nproc)
        cd ..
        zip -r openppp2-centos7.zip bin

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: openppp2-centos7
        path: openppp2-centos7.zip
