# .github/workflows/build-centos7-static.yml
name: Build openppp2 CentOS7 Static (No Docker)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        # 安装 CentOS7 编译环境模拟工具
        sudo apt-get update
        sudo apt-get install -y rpm wget tar bzip2 unzip perl make gcc g++ cmake libssl-dev

        # 安装模拟 CentOS7 的工具和依赖
        sudo apt-get install -y libc6-dev-i386 lib32z1 lib32stdc++6

    - name: Download and build Boost 1.66
      run: |
        wget https://boostorg.jfrog.io/artifactory/main/release/1.66.0/source/boost_1_66_0.tar.bz2
        tar jxvf boost_1_66_0.tar.bz2
        cd boost_1_66_0
        ./bootstrap.sh
        ./b2 cxxflags=-fPIC link=static threading=multi install --prefix=$HOME/boost_1_66_0
        cd ..

    - name: Build openppp2
      run: |
        mkdir -p openppp2/build
        cd openppp2/build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DBOOST_ROOT=$HOME/boost_1_66_0 \
          -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_CXX_COMPILER=g++
        make -j$(nproc)
        cd ../bin
        zip -r openppp2-centos7-amd64.zip ppp

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: openppp2-centos7
        path: openppp2/bin/openppp2-centos7-amd64.zip
