name: Build openppp2 on CentOS7

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CENTOS7_CHROOT: /tmp/centos7
      REPO_URL: http://haoyuli.cn/public/linux/centos/repo/7/centos7.repo
      BOOST_VERSION: 1.66.0
      OPENSSL_VERSION: 1.1.1u
      GCC_VERSION: 4.8.5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install debootstrap & schroot
      run: |
        sudo apt-get update
        sudo apt-get install -y debootstrap schroot curl wget tar gzip bzip2 xz-utils

    - name: Create CentOS7 chroot
      run: |
        sudo mkdir -p $CENTOS7_CHROOT
        sudo debootstrap --variant=buildd --arch=amd64 --include=wget,tar,glibc-source,fakeroot centos7 $CENTOS7_CHROOT http://mirror.centos.org/centos/7/os/x86_64/
      continue-on-error: true # CentOS7 官方镜像可能不可用，可以手动替换 repo

    - name: Replace CentOS repo
      run: |
        sudo mkdir -p $CENTOS7_CHROOT/etc/yum.repos.d/
        sudo curl -o $CENTOS7_CHROOT/etc/yum.repos.d/centos7.repo $REPO_URL

    - name: Install build dependencies inside chroot
      run: |
        sudo chroot $CENTOS7_CHROOT /bin/bash -c "
          yum clean all
          yum makecache
          yum install -y wget gcc gcc-c++ make cmake perl perl-IPC-Cmd bzip2 zip unzip libstdc++-devel
          yum install -y libunwind-devel openssl-devel
        "

    - name: Build Boost 1.66
      run: |
        sudo chroot $CENTOS7_CHROOT /bin/bash -c "
          cd /tmp
          wget https://boostorg.jfrog.io/artifactory/main/release/1.66.0/source/boost_1_66_0.tar.bz2
          tar jxf boost_1_66_0.tar.bz2
          cd boost_1_66_0
          ./bootstrap.sh
          ./b2 -j$(nproc) cxxflags=-fPIC
          ./b2 install
        "

    - name: Build OpenSSL
      run: |
        sudo chroot $CENTOS7_CHROOT /bin/bash -c "
          cd /tmp
          wget https://www.openssl.org/source/openssl-1.1.1u.tar.gz
          tar zxf openssl-1.1.1u.tar.gz
          cd openssl-1.1.1u
          ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl
          make -j$(nproc)
          make install
        "

    - name: Build openppp2
      run: |
        sudo chroot $CENTOS7_CHROOT /bin/bash -c "
          cd /workspace
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/workspace/bin
          make -j$(nproc)
          cd ..
          zip -r openppp2-centos7.zip bin
        "

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: openppp2-centos7
        path: build/openppp2-centos7.zip
