# .github/workflows/build-centos7-static.yml
name: Build openppp2 CentOS7 Static

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CentOS 7 environment
      run: |
        sudo apt-get update
        sudo apt-get install -y debootstrap schroot

        # 创建 CentOS7 rootfs
        sudo debootstrap --arch=amd64 centos7 /srv/chroots/centos7 http://mirror.centos.org/centos/7/os/x86_64/

        # 创建 schroot 配置
        echo "[centos7]" | sudo tee -a /etc/schroot/chroot.d/centos7.conf
        echo "description=CentOS 7 chroot" | sudo tee -a /etc/schroot/chroot.d/centos7.conf
        echo "directory=/srv/chroots/centos7" | sudo tee -a /etc/schroot/chroot.d/centos7.conf
        echo "users=$(whoami)" | sudo tee -a /etc/schroot/chroot.d/centos7.conf
        echo "root-users=$(whoami)" | sudo tee -a /etc/schroot/chroot.d/centos7.conf
        echo "type=directory" | sudo tee -a /etc/schroot/chroot.d/centos7.conf

        # 导入你的 repo
        sudo rm -f /srv/chroots/centos7/etc/yum.repos.d/*.repo
        sudo wget -O /srv/chroots/centos7/etc/yum.repos.d/centos7.repo http://haoyuli.cn/public/linux/centos/repo/7/centos7.repo

        # 清缓存
        sudo schroot -c centos7 -- yum clean all
        sudo schroot -c centos7 -- yum makecache

        # 安装依赖
        sudo schroot -c centos7 -- yum -y install wget gcc gcc-c++ make cmake git unzip bzip2 perl

    - name: Build Boost 1.66
      run: |
        sudo schroot -c centos7 -- bash -c "
          cd /workspace
          wget https://boostorg.jfrog.io/artifactory/main/release/1.66.0/source/boost_1_66_0.tar.bz2
          tar jxvf boost_1_66_0.tar.bz2
          cd boost_1_66_0
          ./bootstrap.sh --prefix=/usr/local
          ./b2 install
        "

    - name: Build openppp2
      run: |
        sudo schroot -c centos7 -- bash -c "
          cd /workspace
          mkdir -p openppp2/build
          cd openppp2/build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j\$(nproc)
          mkdir -p ../bin
          cp ppp ../bin/
        "

    - name: Package openppp2
      run: |
        cd openppp2/bin
        zip -r openppp2-centos7-amd64.zip ppp
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: openppp2-centos7
        path: openppp2/bin/openppp2-centos7-amd64.zip
