name: Build OpenPPP2 CentOS7 Static

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run build in CentOS 7
      run: |
        docker run --rm -v $PWD:/workspace -w /workspace centos:7 /bin/bash -c "
          # 更新基础工具和依赖
          yum install -y epel-release
          yum install -y gcc gcc-c++ make cmake wget tar bzip2 zip unzip curl git \
                         openssl-devel libicu-devel libunwind-devel lrzsz

          # 下载并编译 Boost 1.66
          wget https://boostorg.jfrog.io/artifactory/main/release/1.66.0/source/boost_1_66_0.tar.bz2
          tar jxvf boost_1_66_0.tar.bz2
          cd boost_1_66_0
          ./bootstrap.sh
          ./b2 cxxflags=-fPIC -j\$(nproc)
          ./b2 install
          cd /workspace

          # 创建构建目录
          mkdir -p build && cd build

          # 使用 CMake 构建 openppp2
          cmake .. \
            -DBOOST_ROOT=/workspace/boost_1_66_0 \
            -DCMAKE_BUILD_TYPE=Release

          make -j\$(nproc)

          # 打包生成的二进制文件
          mkdir -p bin
          cp ./ppp/bin/ppp ./bin/
          zip -r openppp2-centos7-amd64.zip ./bin
        "

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: openppp2-centos7-amd64
        path: openppp2-centos7-amd64.zip
