name: Build openppp2 on CentOS 7

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-centos7:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup CentOS 7 environment
      run: |
        sudo apt-get update -y
        sudo apt-get install -y debootstrap schroot

        # 创建一个 CentOS 7 chroot 环境
        sudo debootstrap --arch=amd64 --variant=minbase centos7 ./centos7-root http://haoyuli.cn/public/linux/centos/repo/7/centos7.repo

    - name: Build inside CentOS 7 chroot
      run: |
        sudo chroot ./centos7-root /bin/bash -c "
        yum clean all
        yum install -y wget tar gzip bzip2 gcc gcc-c++ make cmake perl openssl-devel zlib-devel

        # 下载 Boost 1.66
        wget https://boostorg.jfrog.io/artifactory/main/release/1.66.0/source/boost_1_66_0.tar.bz2 -O boost_1_66_0.tar.bz2
        tar jxvf boost_1_66_0.tar.bz2
        cd boost_1_66_0
        ./bootstrap.sh
        ./b2 cxxflags=-fPIC link=static threading=multi install --prefix=/usr/local/boost_1_66_0
        cd ..

        # 克隆 openppp2
        git clone https://github.com/yhvhnl/openppp2.20240704 openppp2
        cd openppp2

        # 创建构建目录
        mkdir -p build && cd build

        # 使用 cmake 构建
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/usr/local/boost_1_66_0
        make -j\$(nproc)

        # 打包二进制
        mkdir -p /workspace/output
        cp -r bin /workspace/output/
        "

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openppp2-centos7
        path: output/
