name: Build OpenPPP2 (CentOS7 Static)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build on CentOS7 Compatible Env
    runs-on: ubuntu-20.04

    steps:
    - name: Wait for available runner (auto retry)
      run: |
        echo "Checking runner availability..."
        for i in {1..10}; do
          if [ -n "$(curl -s -o /dev/null -w '%{http_code}' https://github.com)" ]; then
            echo "✅ Runner ready!"
            break
          fi
          echo "⚠️ Runner not ready yet. Retrying in 30s... (Attempt $i/10)"
          sleep 30
        done

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare build environment
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential wget curl git cmake autoconf automake libtool bzip2

    - name: Download and extract Boost 1.66.0
      run: |
        BOOST_URL="https://sourceforge.net/projects/boost/files/boost/1.66.0/boost_1_66_0.tar.bz2/download"
        wget -O boost_1_66_0.tar.bz2 "$BOOST_URL"
        tar --bzip2 -xf boost_1_66_0.tar.bz2
        cd boost_1_66_0
        ./bootstrap.sh --prefix=/usr/local
        ./b2 -j$(nproc)
        sudo ./b2 install

    - name: Install newer CMake
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.27.8/cmake-3.27.8-linux-x86_64.sh
        sudo bash cmake-3.27.8-linux-x86_64.sh --skip-license --prefix=/usr/local

    - name: Build project
      run: |
        mkdir -p build && cd build
        cmake ..
        make -j$(nproc)

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: openppp2-centos7-static
        path: build/
